# Generated by Django 4.1.1 on 2022-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Debtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.debtor'),
            preserve_default=False,
        ),
    ]
