# Generated by Django 4.1.1 on 2022-10-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_payment_debtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Debtor',
            new_name='debtor',
        ),
    ]
