# Generated by Django 4.1.1 on 2022-10-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_debtor_payment_debtor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debtor',
            old_name='debts',
            new_name='debt',
        ),
    ]
