# Generated by Django 4.1.1 on 2022-10-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_debts_debtor_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='debtor',
            name='insurance',
            field=models.ManyToManyField(to='main_app.insurance'),
        ),
    ]
